networks:
  integration-test:
    driver: bridge

services:
  taxapi_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - .:/go/src/target
    depends_on:
      - taxapi
    networks:
      - integration-test
    env_file:
      - ./test.env
  taxapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - ./test.env
    networks:
      - integration-test
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - integration-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
volumes:
    pgdata: