@HostAddress = http://localhost:8080
### Authorization: Basic user:passwd

GET {{HostAddress}}/hello-world

### Story: EXP01
### As a user, As user, I want to calculate my tax

POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

Response body

```json
{
  "tax": 29000.0,
  "taxRefund": 0.0
}
```
### Story: EXP01-1:
### As user, I want to calculate my tax with Income 2,000,001

POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 2000001.0,
  "wht": 0.0
}

Response body

```json
{
  "tax": 258000.2,
  "taxRefund": 0,
  "taxLevels": [
    {
      "level": "0.00 - 150,000.00",
      "tax": 0
    },
    {
      "level": "150,001.00 - 500,000.00",
      "tax": 50000
    },
    {
      "level": "500,001.00 - 1,000,000.00",
      "tax": 150000
    },
    {
      "level": "1,000,001.00 - 2,000,000.00",
      "tax": 58000.2
    },
    {
      "level": "2,000,001.00 ขึ้นไป",
      "tax": 0
    }
  ]
}
```

### Story: EXP02
### As user, I want to calculate my tax with WHT
POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 25000.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

Response body

```json
{
  "tax": 4000.0,
  "taxRefund": 0.0
}
```

### Story: EXP03
### As user, I want to calculate my tax donation
POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

Response body

```json
{
  "tax": 19000.0,
  "taxRefund": 0.0
}
```

### Story: EXP03-1
### As user, I want to calculate my tax donation and have taxRefund
POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 20000.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

Response body

```json
{
  "tax": 0.0,
  "taxRefund": 1000.00
}
```

### Story: EXP04
### As user, I want to calculate my tax with tax level detail
POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

Response body

```json
{
  "tax": 19000.0,
  "taxLevel": [
    {
      "level": "0-150,000",
      "tax": 0.0
    },
    {
      "level": "150,001-500,000",
      "tax": 19000.0
    },
    {
      "level": "500,001-1,000,000",
      "tax": 0.0
    },
    {
      "level": "1,000,001-2,000,000",
      "tax": 0.0
    },
    {
      "level": "2,000,001 ขึ้นไป",
      "tax": 0.0
    }
  ]
}
```

### Error Validation
### Story: ERROR
### As a user, I want to get error message when I input invalid data such as negative number
POST {{HostAddress}}/tax/calculations
#Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": -500.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": -200000.0
    }
  ]
}

Response body

```json
{
  "message": "Validate Err:WHT is less than 0\nAllowance amount is less than 0"
}
```

### Story: EXP05
### As admin, I want to setting personal deduction ในฐานะ Admin ฉันต้องการตั้งค่าลดหย่อนส่วนตัว
POST {{HostAddress}}/admin/deductions/personal
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": 70000.0
}
//60000
Response body

```json
{
  "personalDeduction": 70000.0
}
```

### Story: EXP05-1
### As admin, I want to list deductions
GET {{HostAddress}}/admin/deductions
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

```json
[
  {
    "id": 1,
    "deductionType": "personal",
    "deductionAmount": 60000,
    "deductionMin": 10000,
    "adeductionMax": 100000
  },
  {
    "id": 2,
    "deductionType": "k-receipt",
    "deductionAmount": 50000,
    "deductionMin": 0,
    "adeductionMax": 100000
  }
]
```

Story: EXP05-2 / 3
- [ ] แอดมิน สามารถกำหนดค่าลดหย่อนส่วนตัวได้โดยไม่เกิน 100,000 บาท
- [ ] ค่าลดหย่อนส่วนตัวต้องมีค่ามากกว่า 10,000 บาท
### Story: EXP05-2
### As admin, I want to setting personal deduction more than 100,000
POST {{HostAddress}}/admin/deductions/personal
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": 100001.0
}

Response body

```json
{
  "message": "personal deduction must be less than 100000.00"
}
```

### Story: EXP05-3
### As admin, I want to setting personal deduction less than 10,000
POST {{HostAddress}}/admin/deductions/personal
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": 9999.0
}

Response body

```json
{
  "message": "personal deduction must be less than 100000.00"
}
```

### Story: EXP06
### * As user, I want to calculate my tax with csv
### * ในฐานะผู้ใช้ ฉันต้องการคำนวนภาษีด้วยข้อมูลที่ upload เป็น csv และมี validation เช่น ใส่ empty ไม่ได้ หรือ ใส่ข้อมูลผิด format ไม่ได้
POST {{HostAddress}}/tax/calculations/upload-csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="taxFile"; filename="taxes.csv" 
Content-Type: text/csv

< ./sampleCSV/taxes.csv 
------WebKitFormBoundary7MA4YWxkTrZu0gW--

Response body

```json
 "taxes": [
    {
      "totalIncome": 500000.0,
      "tax": 29000.0
    },
    ...
  ]

full

{
  "taxes": [
    {
      "totalIncome": 500000,
      "tax": 29000,
      "taxRefund": 0
    },
    {
      "totalIncome": 600000,
      "tax": 0,
      "taxRefund": 3000
    },
    {
      "totalIncome": 750000,
      "tax": 3750,
      "taxRefund": 0
    }
  ]
}
```

### Story: EXP07
### As user, I want to calculate my tax with tax level detail
### ในฐานะผู้ใช้ ฉันต้องการคำนวนภาษีจาก ข้อมูลที่ส่งให้พร้อมค่าลดหย่อน พร้อมระบุรายละเอียดของขั้นบันใดภาษี

POST {{HostAddress}}/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "k-receipt",
      "amount": 50000.0
    },
    {
      "allowanceType": "donation",
      "amount": 100000.0
    }
  ]
}

Response body

```json
{
  "tax": 14000.0,
  "taxLevel": [
    {
      "level": "0-150,000",
      "tax": 0.0
    },
    {
      "level": "150,001-500,000",
      "tax": 14000.0
    },
    {
      "level": "500,001-1,000,000",
      "tax": 0.0
    },
    {
      "level": "1,000,001-2,000,000",
      "tax": 0.0
    },
    {
      "level": "2,000,001 ขึ้นไป",
      "tax": 0.0
    }
  ]
}
```

### Story: EXP08-0
###  As admin, I want to setting k-receipt deduction ในฐานะ Admin ฉันต้องการตั้งค่า k-receipt สำหรับลดหย่อน
POST {{HostAddress}}/admin/deductions/k-receipt
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": 70000.0
}

Response body

//50000

```json
{
  "kReceipt": 70000.0
}
```



### Story: EXP08-1
###- [ ] แอดมิน สามารถกำหนด k-receipt สูงสุดได้ แต่ไม่เกิน 100,000 บาท
###  As admin, I want to setting k-receipt deduction more than 100,000
POST {{HostAddress}}/admin/deductions/k-receipt
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": 100001.0
}

Response body

```json
{
  "message": "k-receipt deduction must be less than 100,000.00"
}
```

### Story: EXP05-3
### As admin, I want to setting personal deduction less than 0.0
POST {{HostAddress}}/admin/deductions/k-receipt
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "amount": -1.0
}

Response body

```json
{
  "message": "k-receipt deduction must be greater than 0.00"
}
```