@HostAddress = http://localhost:8080
### Authorization: Basic user:passwd

GET {{HostAddress}}/hello-world

### Story: EXP01
### As a user, As user, I want to calculate my tax

POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

Response body

```json
{
  "tax": 29000.0,
  "taxRefund": 0.0
}
```
### Story: EXP01-1:
### As user, I want to calculate my tax with Income 2,000,001

POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 2000001.0,
  "wht": 0.0
}

Response body

```json
{
  "tax": 258000.2,
  "taxRefund": 0,
  "taxLevels": [
    {
      "level": "0.00 - 150,000.00",
      "tax": 0
    },
    {
      "level": "150,001.00 - 500,000.00",
      "tax": 50000
    },
    {
      "level": "500,001.00 - 1,000,000.00",
      "tax": 150000
    },
    {
      "level": "1,000,001.00 - 2,000,000.00",
      "tax": 58000.200000000004
    },
    {
      "level": "2,000,001.00 ขึ้นไป",
      "tax": 0
    }
  ]
}
```

### Story: EXP02
### As user, I want to calculate my tax with WHT
POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 25000.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

Response body

```json
{
  "tax": 4000.0,
  "taxRefund": 0.0
}
```

### Story: EXP03
### As user, I want to calculate my tax donation
POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

Response body

```json
{
  "tax": 19000.0,
  "taxRefund": 0.0
}
```

### Story: EXP03-1
### As user, I want to calculate my tax donation and have taxRefund
POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 20000.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

Response body

```json
{
  "tax": 0.0,
  "taxRefund": 1000.00
}
```

### Error Validation
### Story: ERROR
### As a user, I want to get error message when I input invalid data such as negative number
POST {{HostAddress}}/tax/calculations
Authorization: Basic YWRtaW5UYXg6YWRtaW4h
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": -500.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": -200000.0
    }
  ]
}